stages:
  - lint
  - test

golangci-lint:
    image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
    stage: lint
    script:
      - golangci-lint run ./...

integration-test:
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_DRIVER: overlay2 
  image: tiangolo/docker-with-compose
  stage: test
  before_script:
    - docker info
    - docker-compose --version
  script:
    - make test
