global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'calendar_api'
    static_configs:
      - targets: ['calendar_api:8888']

  - job_name: 'calendar_scheduler'
    static_configs:
      - targets: ['calendar_scheduler:8888']