version: "3"
networks:
  calendar_nw:
    driver: bridge

services:
  postgres:
    image: postgres:11
    restart: on-failure
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./env/db.env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calendar_nw
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    networks:
      - calendar_nw
  calendar_api:
    build: ../calendar-api
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 9999:9999
    expose:
      - 9999
    env_file:
      - ./env/api.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh postgres:5432 -- /calendar/api --config=config.json"]
    networks:
      - calendar_nw
  calendar_scheduler:
    build: ../calendar-scheduler
    depends_on:
      - rabbitmq
      - calendar_api
    restart: on-failure
    env_file: 
      - ./env/scheduler.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh rabbitmq:15672 -- /calendar/scheduler --config=config.json"]
    networks:
      - calendar_nw
  calendar_test:
    build: ../calendar-test
    depends_on:
      - rabbitmq
      - calendar_api
      - calendar_scheduler
    env_file:
      - ./env/test.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh rabbitmq:15672 -- /calendar/test --config=config.json"]
    networks:
       - calendar_nw