version: "3"
networks:
  calendar_nw:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./env/db.env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calendar_nw
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    networks:
      - calendar_nw
  calendar_api:
    build: ../calendar-api
    depends_on:
      - postgres
    restart: on-failure
    expose:
      - 8888
      - 9999
    ports:
      - "8888:8888"
      - "9999:9999"
    env_file:
      - ./env/api.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh postgres:5432 -- /calendar/api --config=config.json"]
    networks:
      - calendar_nw
  calendar_scheduler:
    build: ../calendar-scheduler
    depends_on:
      - rabbitmq
      - calendar_api
    restart: on-failure
    env_file: 
      - ./env/scheduler.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh calendar_api:8888 -- /calendar/scheduler --config=config.json"]
    networks:
      - calendar_nw
  calendar_client:
    build: ../calendar-client
    depends_on:
      - rabbitmq
      - calendar_scheduler
    restart: on-failure
    env_file: 
      - ./env/client.env
    entrypoint: ["bash", "-c", "/usr/bin/wait-for-it.sh rabbitmq:15672 -- /calendar/client --config=config.json"]
    networks:
      - calendar_nw
  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # - '--web.console.libraries=/etc/prometheus/console_libraries'
      # - '--web.console.templates=/etc/prometheus/consoles'
      # - '--storage.tsdb.retention=120h'
      # - '--web.enable-lifecycle'
    # restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - calendar_nw